export const RECEIVE_TODO_SUCCESS = 'RECEIVE_TODO_SUCCESS';
export const RECEIVE_TODO_FAILURE = 'RECEIVE_TODO_FAILED';
export const IS_LOADING = 'IS_LOADING';

export const IS_FILTERED = 'IS_FILTERED';
export const PAGE_UPDATE = 'PAGE_UPDATE';
export const NUMBER_ELEMENT_DISPLAY = 'NUMBER_ELEMENT_DISPLAY';